keley:
    resource: "@KeleyBundle/Resources/config/routing.yml"
    prefix:   /

rest:
    resource: "@KeleyBundle/Resources/config/routing_rest.yml"
    type: rest
    prefix:   /api

app:
    resource: '@AppBundle/Controller/'
    type: annotation




